site_name: Home Buttons

repo_url: https://github.com/nplan/HomeButtons
repo_name: nplan/HomeButtons

nav:
  - Home: index.md
  - Getting Started: setup.md
  - User Guide: user_guide.md
  - Tech Specs: specs.md
  - Firmware Update: update.md
  - MQTT Topics: mqtt_topics.md
  - Hardware Hacks: hardware_hacks.md
  - Help: help.md

theme:
  name: material
  logo: assets/home_buttons_logo.svg
  favicon: assets/home_buttons_logo.svg
  features:
    - content.code.annotate 
    - navigation.indexes
  
    # Palette toggle for light mode
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: cyan
      accent: orange


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-F5LT7JQ5LS

